// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvo5kdFUle8cgkWEUkUOuj89Np08yLdnE',
    appId: '1:793739497223:web:a6ce644fc86abbb318ffa2',
    messagingSenderId: '793739497223',
    projectId: 'subwallet-app-01',
    authDomain: 'subwallet-app-01.firebaseapp.com',
    storageBucket: 'subwallet-app-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3daeok5DCkxle5UIWCFzLgDix5UcXfM',
    appId: '1:793739497223:android:dae4046f67a18f5f18ffa2',
    messagingSenderId: '793739497223',
    projectId: 'subwallet-app-01',
    storageBucket: 'subwallet-app-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRE5KtjNB9nYalP-Tnm6z3SfvLYze_ZWk',
    appId: '1:793739497223:ios:07145900a126a94018ffa2',
    messagingSenderId: '793739497223',
    projectId: 'subwallet-app-01',
    storageBucket: 'subwallet-app-01.firebasestorage.app',
    iosBundleId: 'com.example.subwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRE5KtjNB9nYalP-Tnm6z3SfvLYze_ZWk',
    appId: '1:793739497223:ios:07145900a126a94018ffa2',
    messagingSenderId: '793739497223',
    projectId: 'subwallet-app-01',
    storageBucket: 'subwallet-app-01.firebasestorage.app',
    iosBundleId: 'com.example.subwallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvo5kdFUle8cgkWEUkUOuj89Np08yLdnE',
    appId: '1:793739497223:web:fad34f858cca157118ffa2',
    messagingSenderId: '793739497223',
    projectId: 'subwallet-app-01',
    authDomain: 'subwallet-app-01.firebaseapp.com',
    storageBucket: 'subwallet-app-01.firebasestorage.app',
  );
}
